name: Build ISO
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed
    branches:
      - main

env:
  IMAGE_NAME: hypr-blue
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  FEDORA_MAJOR_VERSION: 42

jobs:
  build-iso:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.2
        id: build
        with:
          arch: x86_64
          image_name: ${{ env.IMAGE_NAME }}
          image_repo: ${{ env.IMAGE_REGISTRY }}
          image_tag: latest
          version: ${{ env.FEDORA_MAJOR_VERSION }}
          variant: Kinoite
          iso_name: ${{ env.IMAGE_NAME }}-${{ env.FEDORA_MAJOR_VERSION }}.iso
          enable_cache_dnf: "false"
          enable_cache_skopeo: "false"
          enable_flatpak_dependencies: "false"
          enrollment_password: "universalblue"
          secure_boot_key_url: 'https://github.com/ublue-os/akmods/raw/main/certs/public_key.der'
          
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.FEDORA_MAJOR_VERSION }}.iso
          path: ${{ steps.build.outputs.iso_path }}
          if-no-files-found: error
          retention-days: 7
          compression-level: 0